### PR TITLE
MAINT: update logo and favicon

### PR DESCRIPTION
**Pull request by bsipocz**
Tuned down the resolution of the original logo file, let me know if it was too much.

### CODE REVIEW

**Comment by vandesai1** [comment]
Looks great! When the Fornax website is more developed, we can think about making the logo a link to it. But for now, I think we are good to go!

**Review by vandesai1 — APPROVED** [review]
Looks great!

**Comment by bsipocz** [comment]
I'll iterate a bit more on the favicon as it looks really bad for me (too busy for the size of it). I'll either use a better resolution one, or reuse the old logo as it's less busy

**Comment by vandesai1** [comment]
The favicon looks good to me!

**Review by vandesai1 — COMMENTED** [review]
The favicon looks good!

**Pull request merged**
